import 'package:equatable/equatable.dart';

abstract class UsersEvent extends Equatable {
  const UsersEvent();

  @override
  List<Object?> get props => [];
}

class LoadUsersEvent extends UsersEvent {
  const LoadUsersEvent();
}

class CreateUserEvent extends UsersEvent {
  final String email;
  final String displayName;
  final String role;
  final String title;
  final String photoUrl;
  final String password;

  /// True when the admin typed the password themselves — it is used directly
  /// as the user's final password (no forced first-login reset) and encoded in
  /// the share QR. False when the password was generated by the panel
  /// (temporary first-login code flow preserved).
  final bool manualPassword;

  const CreateUserEvent({
    required this.email,
    required this.displayName,
    required this.role,
    this.title = '',
    this.photoUrl = '',
    this.password = '',
    this.manualPassword = false,
  });

  @override
  List<Object?> get props =>
      [email, displayName, role, title, photoUrl, password, manualPassword];
}

class SendVerificationCodeEvent extends UsersEvent {
  final String uid;
  const SendVerificationCodeEvent(this.uid);

  @override
  List<Object?> get props => [uid];
}

class UpdateUserEvent extends UsersEvent {
  final String uid;
  final String? email;
  final String? displayName;
  final String? title;
  final String? photoUrl;
  final String? role;

  /// New password to assign to the Auth account. When null/empty the current
  /// password is left untouched.
  final String? password;

  const UpdateUserEvent({
    required this.uid,
    this.email,
    this.displayName,
    this.title,
    this.photoUrl,
    this.role,
    this.password,
  });

  @override
  List<Object?> get props =>
      [uid, email, displayName, title, photoUrl, role, password];
}

class DeleteUserEvent extends UsersEvent {
  final String uid;
  const DeleteUserEvent(this.uid);

  @override
  List<Object?> get props => [uid];
}

class ClearVerificationCodeEvent extends UsersEvent {
  const ClearVerificationCodeEvent();
}
